### ISSUE TITLE
@-prefixed packages got saved in the wrong path

### ISSUE THREAD

**Issue by mcollina** [mafintosh/ims#5]
As an example `@types/pino`  get saved in `node_modules/@types/pino/pino` instead of `node_modules/@types/pino`.

**Comment by mafintosh** [comment]
Hmm.. can't repro this. I tried running `ims` inside the fastify repo to repro, but it all seemed to install correctly.

**Comment by mcollina** [comment]
uh, maybe something bad happened, will see if I can repro again.
